provider: "anthropic"
model: "claude-3-5-sonnet-20241022"
temperature: 0
tartxt_config:
  script_path: /Users/jim/src/apps/c4h/c4h_agents/skills/tartxt.py
  exclusions:
    - '**/node_modules/**'
    - '**/.git/**'
    - '**/__pycache__/**'
    - '**/*.pyc'
    - '**/package-lock.json'
    - '**/dist/**'
    - '**/.DS_Store'
    - '**/README.md'
    - '**/workspaces/**'
    - '**/backup_txt/**'
prompts:
  system: |
    You are a project discovery agent.
    You analyze project structure and files to understand:
    1. Project organization
    2. File relationships
    3. Code dependencies
    4. Available functionality