# Path: c4h_services/examples/config/workflow_coder_01.yml

# Project settings
project_path: "./tests/test_projects/"  # Using test project

# Intent description
intent:
  description: |
    Add logging to all functions:
    - Replace print statements with logging
    - Add logging configuration

# Discovery agent configuration
llm_config:
  agents:
    discovery:
      temperature: 0
      tartxt_config:
        script_path: "./c4h_agents/skills/tartxt.py"  # Explicit path to tartxt.py
        input_paths: ["./"]  # Scan everything in project path
        exclusions: ["**/__pycache__/**"]  # Skip cache directories

    solution_designer:
      temperature: 0.1

    coder:
      temperature: 0

runtime:
  workflow:
    storage:
      enabled: true
      root_dir: "workspaces/workflows"
      format: "yymmdd_hhmm_{workflow_id}"
      retention:
        max_runs: 10
        max_days: 30
      error_handling:
        ignore_storage_errors: true
        log_level: "ERROR"

# Backup settings
backup:
  enabled: true
  path: "workspaces/backups"