# Path: c4h_services/examples/config/workflow_coder_01.yml

# Project settings
project_path: "./tests/test_projects/"  # Using test project

# Intent description
intent:
  description: "Add logging to all functions"
  requirements:
    - "Replace print statements with logging"
    - "Add logging configuration"

# Discovery agent configuration
llm_config:
  agents:
    discovery:
      temperature: 0
      tartxt_config:
        script_path: "./c4h_agents/skills/tartxt.py"  # Explicit path to tartxt.py
        input_paths: ["./"]  # Scan everything in project path
        exclusions: ["**/__pycache__/**"]  # Skip cache directories

    solution_designer:
      temperature: 0.1

    coder:
      temperature: 0

# Backup settings
backup:
  enabled: true
  path: "workspaces/backups"