# Path: c4h_services/examples/config/lineage_test_workflow.yml

# Project settings
project_path: "./tests/test_projects/"  # Using test project

# Intent description
intent:
  description: |
    Add logging to all functions with lineage tracking:
    - Replace print statements with logging
    - Add logging configuration
    - Enable lineage tracking for observability

llm_config:
  default_provider: "anthropic"
  default_model: "claude-3-5-sonnet-20241022"
  agents:
    discovery:
      temperature: 0
      tartxt_config:
        script_path: "./c4h_agents/skills/tartxt.py"  # Explicit path to tartxt.py
        input_paths: ["./"]  # Scan everything in project path
        exclusions: ["**/__pycache__/**"]  # Skip cache directories
    solution_designer:
      provider: "anthropic"
      model: "claude-3-7-sonnet-20250219"
    coder:
      provider: "anthropic"
      model: "claude-3-5-sonnet-20241022"

runtime:
  # Workflow storage configuration
  workflow:
    storage:
      enabled: true
      root_dir: "workspaces/workflows"
      format: "yymmdd_hhmm_{workflow_id}"
      retention:
        max_runs: 10
        max_days: 30
      error_handling:
        ignore_storage_errors: true
        log_level: "ERROR"
        
  # Lineage tracking configuration  
  lineage:
    enabled: true
    namespace: "c4h_workflow"
    backend:
      type: "file"  # File-based storage is more reliable for initial testing
      path: "workspaces/lineage"  # Use explicit relative path
    error_handling:
      ignore_failures: true  # Don't let lineage errors affect workflow
      log_level: "ERROR"
    # Context enrichment - always include these fields in lineage records  
    context:
      include_metrics: true
      include_token_usage: true
      record_timestamps: true

# Backup settings  
backup:
  enabled: true
  path: "./workspaces/backups"  # Use explicit relative path

# Logging settings
logging:
  level: "DEBUG"
  format: "structured"
  agent_level: "DEBUG"