# Path: c4h_services/examples/config/workflow_coder_self_01.yml

project:
  path: "/Users/jim/src/apps/c4h_ai_dev"  
  workspace_root: "workspaces"

providers:
  anthropic:
    api_base: "https://api.anthropic.com"
    default_model: "claude-3-opus-20240229"

llm_config:
  default_provider: "anthropic"
  default_model: "claude-3-opus-20240229"
  
  agents:
    semantic_iterator:
      temperature: 0
      extractor_config:
        mode: "slow"
        allow_fallback: true
    discovery:
      provider: "anthropic"
      model: "claude-3-opus-20240229"
      temperature: 0
      tartxt_config:
        # This is a relative path from project root
        script_path: "c4h_agents/skills/tartxt.py"
        # Input paths relative to project root
        input_paths: 
          - "c4h_agents"
          - "c4h_services" 
          - "config"
          - "docs"
        # Can be string or list, normalized by discovery agent
        exclusions: "**/__pycache__/**,**/.git/**,**/*.pyc,**/workspaces/**,**/.pytest_cache/**, *.md"
        output_type: "stdout"
        output_file: null  # Only used if output_type is "file"

    solution_designer:
      provider: "anthropic"
      model: "claude-3-5-sonnet-latest"
      temperature: 0.1
      intent:
        description: |
          - Design Constraints - read Agent Design Principles, all designs must be constrained by those principles
          - Compare any proposed solution against the original code, do not lose any functionality, do not overdesign, stick to the principles
          - NEVER lose existing functionality, or break existing code
          Intent - the logging is too long, i want to better control the volume of log
          - we are running this through prefect_runner, so it needs to support multi modal logging flags --log debug|trace|default
          If debug is enabled then print out the full prompt
          If trace i'm interested mainly in the trace of the logic flow, and enough content to get context
          If default set or no option given, give minimal logging, such as warnings & errors, and final result
          only update the logging, dont lose functionality
          make sure the command line is honored by the agents

backup:
  enabled: true
  path: "workspaces/backups"

logging:
  level: "INFO"
  format: "structured"
  agent_level: "DEBUG"