provider: "anthropic"
model: "claude-3-opus-20240229"
temperature: 0

# Active execution plan for the coder orchestrator that implements the event logging
execution_plan:
  enabled: true
  steps:
    - name: "extract_changes"
      type: "skill"
      skill: "semantic_iterator"
      params:
        input_data: "{{context.input_data.response}}"
        format: "json"
      output_field: "iterator_result"
    
    - name: "process_first_change" 
      type: "skill"
      skill: "asset_manager"
      params:
        action: "write"
        path: "{{iterator_result.value[0].file_path}}"
        content: "{{iterator_result.value[0].content}}"
      output_field: "results.changes.0"
      
    - name: "process_second_change" 
      type: "skill"
      skill: "asset_manager"
      params:
        action: "write"
        path: "{{iterator_result.value[1].file_path}}"
        content: "{{iterator_result.value[1].content}}"
      output_field: "results.changes.1"
      
    - name: "process_third_change" 
      type: "skill"
      skill: "asset_manager"
      params:
        action: "write"
        path: "{{iterator_result.value[2].file_path}}"
        content: "{{iterator_result.value[2].content}}"
      output_field: "results.changes.2"

prompts: # Prompts might be needed for specific steps or error handling
  system: |
    You are an expert code modification agent. Your task is to safely and precisely apply code changes.
    You receive changes in this exact JSON structure:
    {
      "changes": [
        {
          "file_path": "exact path to file",
          "type": "modify",
          "description": "change description",
          "content": "complete file content" # Or 'diff' depending on input needs
        }
      ]
    }

    Rules:
    1. Always expect input in the above JSON format
    2. If input is a string, parse it as JSON first
    3. Preserve existing functionality unless explicitly told to change it
    4. Maintain code style and formatting
    5. Apply changes exactly as specified
    6. Handle errors gracefully with backups
    7. Validate code after changes
